import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { SignInButton } from "@clerk/clerk-react";
import { useUser } from "@clerk/nextjs/dist/client-boundary/hooks";
import {SignOutButton} from "./signout";


const Home: NextPage = () => {
  
  const user = useUser();

  const {data} = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
    
          <div>
            
          </div>
          <div>
            {data?.map((posts)=>(<div key={posts.id}>{posts.content}</div>
            ))}
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          </div>
      </main>
    </>
  );
};

export default Home;
